# Generated by Django 2.1.1 on 2018-09-13 18:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20180913_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
