# Generated by Django 2.1.1 on 2018-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_portfolio_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.TextField(blank=True, default='aurthurm/', help_text='Github link as: username/repository', verbose_name='Github url'),
        ),
    ]
