# Generated by Django 2.1.1 on 2018-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_auto_20180915_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.CharField(blank=True, default='aurthurm/', help_text='Github link as: username/repository', max_length=255, verbose_name='Github url'),
        ),
    ]
