# Generated by Django 2.1.1 on 2018-09-15 18:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHeadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=255, verbose_name='Services Title')),
                ('teaching_title', models.CharField(max_length=255, verbose_name='Teaching Title')),
                ('technologies_title', models.CharField(max_length=255, verbose_name='Technologies Title')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Services Title')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Subjet Title')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Teaching Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('tag', models.CharField(max_length=255, verbose_name='tag')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TechTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Image Title')),
                ('image', models.ImageField(blank=True, help_text='Used for illustration.', upload_to=home.models.image_upload_to_dispatcher, verbose_name='image')),
            ],
        ),
    ]
