# Generated by Django 2.1.1 on 2018-09-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingentry',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='teachingentry',
            name='tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='teachingentry',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Teaching Title'),
        ),
    ]
