# Generated by Django 2.1.1 on 2018-09-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180915_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_subject', to='home.Subject'),
        ),
    ]
